base_url: "https://api.openai.com/v1"
max_seq_length: 8192
max_prompt_length: 8196
temperature: 0.6
tensor_parallel_size: 1
learning_rate: 5e-6
adam_beta1: 0.9
adam_beta2: 0.99
weight_decay: 0.1
warmup_ratio: 0.1
lr_scheduler_type: "cosine"
optim: "paged_adamw_8bit"
logging_steps: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
num_generations: 6
max_completion_length: 1024
max_steps: 100
save_steps: 100
max_grad_norm: 0.1
report_to: "none"
output_dir: "outputs"