base_url: "https://api.openai.com/v1"
max_seq_length: 2048
max_prompt_length: 526
temperature: 0.6
tensor_parallel_size: 1
learning_rate: 0.000005
adam_beta1: 0.9
adam_beta2: 0.999
weight_decay: 0.1
warmup_ratio: 0.1
lr_scheduler_type: "cosine"
optim: "adamw_8bit"
logging_steps: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
num_generations: 4
max_completion_length: 1522
max_steps: 500
save_steps: 250
max_grad_norm: 1.0
report_to: "none"
output_dir: "outputs"